GET http://localhost:3000/api/tasks
Content-Type: application/json

### GET todas las tareas del usuario

GET http://localhost:3000/api/tasks/user/5
Content-Type: application/json

### GET info inicial

GET http://localhost:3000/api/tasks/progress/6


### POST nueva tarea
POST http://localhost:3000/api/tasks/assign
Content-Type: application/json

{
  "studentId": 3,
  "subjectId": 1,
  "comments": "Completar el capítulo 3.",
  "deadline": "2024-12-10"
}

###### PUT actualizar tarea

PUT http://localhost:3000/api/tasks/28
Content-Type: application/json

{
  "punctuation": 9,
  "submission": "Contenido de la entrega"
}

### DELETE tarea
DELETE http://localhost:3000/api/tasks/26
Content-Type: application/json

###
GET http://localhost:3000/api/users/6/details
Content-Type: application/json

###
### Obtener estudiantes por profesor
GET http://localhost:3000/api/professors/3/students
Content-Type: application/json
